# Site settings
title: Homescreen
email: info@homescreen.rocks
description: > # this means to ignore newlines until "baseurl:"
  Your favorite touchscreen app for all you home functions. 
  See the outside weather, see when your underground or bus departs, 
  control your Philips hue lights or just to deeply impress your friends.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://homescreen.rocks" # the base hostname & protocol for your site

# User setting
owner: Homescreen Rocks
email: info@homescreen.rocks
facebook_username:
twitter_username:
github_username: homescreenrocks
address:
  - line:
  - line:
  # Feel free to add more lines here 
telephone:
copyright: 2016 by Homescreen Rocks

# API settings
google_api_key:

# Build settings
markdown: kramdown