name: Homescreen
author: homescreen.rocks
baseurl: 
description: Your favorite touchscreen app for all you home functions. See the outside weather, see when your underground or bus departs, control your Philips hue lights or just to deeply impress your friends.
github: https://github.com/homescreenrocks/homescreen
facebook: http://www.facebook.com
email: info[at]homescreen.rocks
location: 42°2'16"N   70°12'47"W
#disqus: diqus-username

##Make sure to edit the above fields, especially for disqus.


highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions: ["tables"]

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
